export const GET_PHASES_REQUEST = 'GET_PHASES_REQUEST'
export const GET_PHASES_SUCCESS = 'GET_PHASES_SUCCESS'
export const GET_PHASES_FAILURE = 'GET_PHASES_FAILURE'

export const GET_WEEKS_REQUEST = 'GET_WEEKS_REQUEST'
export const GET_WEEKS_SUCCESS = 'GET_WEEKS_SUCCESS'
export const GET_WEEKS_FAILURE = 'GET_WEEKS_FAILURE'

export const GET_DAYS_REQUEST = 'GET_DAYS_REQUEST'
export const GET_DAYS_SUCCESS = 'GET_DAYS_SUCCESS'
export const GET_DAYS_FAILURE = 'GET_DAYS_FAILURE'

export const CHOOSE_PHASE = 'CHOOSE_PHASE'
export const CHOOSE_WEEK = 'CHOOSE_WEEK'
export const CHOOSE_DAY = 'CHOOSE_DAY'
