export const GET_PHASES_REQUEST = 'GET_PHASES_REQUEST'
export const GET_PHASES_SUCCESS = 'GET_PHASES_SUCCESS'
export const GET_PHASES_FAILURE = 'GET_PHASES_FAILURE'

export const GET_WEEKS_REQUEST = 'GET_WEEKS_REQUEST'
export const GET_WEEKS_SUCCESS = 'GET_WEEKS_SUCCESS'
export const GET_WEEKS_FAILURE = 'GET_WEEKS_FAILURE'

export const GET_DAYS_REQUEST = 'GET_DAYS_REQUEST'
export const GET_DAYS_SUCCESS = 'GET_DAYS_SUCCESS'
export const GET_DAYS_FAILURE = 'GET_DAYS_FAILURE'

export const GET_DAY_REQUEST = 'GET_DAY_REQUEST'
export const GET_DAY_SUCCESS = 'GET_DAY_SUCCESS'
export const GET_DAY_FAILURE = 'GET_DAY_FAILURE'

export const STATUS_REQUEST = 'STATUS_REQUEST'
export const STATUS_SUCCESS = 'STATUS_SUCCESS'
export const STATUS_FAILURE = 'STATUS_FAILURE'

export const CHOOSE_PHASE = 'CHOOSE_PHASE'
export const CHOOSE_WEEK = 'CHOOSE_WEEK'
export const CHOOSE_DAY = 'CHOOSE_DAY'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CREATEUSER_REQUEST = 'CREATEUSER_REQUEST'
export const CREATEUSER_SUCCESS = 'CREATEUSER_SUCCESS'
export const CREATEUSER_FAILURE = 'CREATEUSER_FAILURE'


export const GETALLDAYS_REQUEST = 'GETALLDAYS_REQUEST'
export const GETALLDAYS_SUCCESS = 'GETALLDAYS_SUCCESS'
export const GETALLDAYS_FAILURE = 'GETALLDAYS_FAILURE'

